[advisories]
ignore = [
  # As the rust community considers the paste crate 'done', we can safely ignore this warning.
  # see https://users.rust-lang.org/t/paste-alternatives/126787/2
  "RUSTSEC-2024-0436",
]
